### ISSUE TITLE
1.0.2 package never made it to packages.ros.org 

### ISSUE THREAD

**Issue by mherrb** [TheDash/pr2_navigation_apps-release#1]
Hi,

it looks like the newly released packages never made it to packages.ros.org which still has ros-hydro-pr2-navigation-apps 1.0.1 only.

**Comment by TheDash** [comment]
My first question would be to see if they are still updating the debs for Hydro or not. I'll have to check that out. Otherwise, I'll do a re-release.

**Comment by TheDash** [comment]
That's strange.. it's appearing here http://www.ros.org/debbuild/hydro.html under 1.0.2 but on the repo it's only 1.0.1 I'll ask Tully about this one.

**Comment by mherrb** [comment]
Hi Devon,

any news on that issue. Can we expect that the updated hydro binary packages will show up on packages.ros.org in the near future ?

**Comment by TheDash** [comment]
Hi,

see http://www.ros.org/debbuild/hydro.html for packages in the future. pr2_navigation is building 1.0.2-1 but the public Hydro debs haven't been synced yet. You can obtain the package by using the shadow fixed repository or ask Tully what the status is on that one.

**Comment by tfoote** [comment]
This update is still being held in the hydro testing repository. Once other packages regressions have been resolved we'll be ready to sync: http://lists.ros.org/pipermail/ros-release/2015-May/004631.html

**Comment by mherrb** [comment]
Too old. Can be closed.
